// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using scryrall_admin.Persistence;

#nullable disable

namespace scryrall_admin.Migrations
{
    [DbContext(typeof(ScryFallDbContext))]
    partial class ScryFallDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("scryrall_admin.Models.Carta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Cartas");
                });

            modelBuilder.Entity("scryrall_admin.Models.Colecao", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("Ano")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Colecoes");
                });

            modelBuilder.Entity("scryrall_admin.Models.Idioma", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<int?>("CartaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CartaId");

                    b.ToTable("Idioma");
                });

            modelBuilder.Entity("scryrall_admin.Models.Ilustrador", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Ilustrador");
                });

            modelBuilder.Entity("scryrall_admin.Models.Link", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("scryrall_admin.Models.RegrasEspeciais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CartaId");

                    b.ToTable("RegrasEspeciais");
                });

            modelBuilder.Entity("scryrall_admin.Models.ToolBox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CartaId");

                    b.ToTable("ToolBoxes");
                });

            modelBuilder.Entity("scryrall_admin.Models.Colecao", b =>
                {
                    b.HasOne("scryrall_admin.Models.Carta", "Carta")
                        .WithOne("Colecao")
                        .HasForeignKey("scryrall_admin.Models.Colecao", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carta");
                });

            modelBuilder.Entity("scryrall_admin.Models.Idioma", b =>
                {
                    b.HasOne("scryrall_admin.Models.Carta", null)
                        .WithMany("Idiomas")
                        .HasForeignKey("CartaId");
                });

            modelBuilder.Entity("scryrall_admin.Models.Ilustrador", b =>
                {
                    b.HasOne("scryrall_admin.Models.Carta", "Carta")
                        .WithOne("Ilustrador")
                        .HasForeignKey("scryrall_admin.Models.Ilustrador", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carta");
                });

            modelBuilder.Entity("scryrall_admin.Models.Link", b =>
                {
                    b.HasOne("scryrall_admin.Models.Carta", "Carta")
                        .WithOne("Link")
                        .HasForeignKey("scryrall_admin.Models.Link", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carta");
                });

            modelBuilder.Entity("scryrall_admin.Models.RegrasEspeciais", b =>
                {
                    b.HasOne("scryrall_admin.Models.Carta", "Carta")
                        .WithMany("RegrasEspeciais")
                        .HasForeignKey("CartaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carta");
                });

            modelBuilder.Entity("scryrall_admin.Models.ToolBox", b =>
                {
                    b.HasOne("scryrall_admin.Models.Carta", "Carta")
                        .WithMany("ToolBoxes")
                        .HasForeignKey("CartaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carta");
                });

            modelBuilder.Entity("scryrall_admin.Models.Carta", b =>
                {
                    b.Navigation("Colecao")
                        .IsRequired();

                    b.Navigation("Idiomas");

                    b.Navigation("Ilustrador")
                        .IsRequired();

                    b.Navigation("Link")
                        .IsRequired();

                    b.Navigation("RegrasEspeciais");

                    b.Navigation("ToolBoxes");
                });
#pragma warning restore 612, 618
        }
    }
}
